/**
 * Convert the hero's script phrase into a SINGLE-STROKE centreline path, so the
 * thread can literally write the words.
 *
 *   npm run lettering
 *
 * Why not the display font: an outline font gives glyph *contours*, so stroking
 * one draws the outside edge of each letter — two parallel lines per stroke.
 * That reads as hairline lettering, never as a thread. Hershey fonts are
 * engraving fonts: one polyline down the middle of each stroke, exactly what a
 * needle would trace.
 *
 * Hershey's raw polylines are coarse (they were digitised for pen plotters in
 * 1967), so every stroke is refitted as a Catmull-Rom spline. That is what
 * turns an angular plot into continuous handwriting.
 *
 * Runs at author time; the generated path is committed, so visitors download
 * neither the font nor the generator.
 */

import { readFile, writeFile } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Must match `home.hero.script` in src/content/home.en.ts. */
const PHRASE = 'The same cloth,'
/** Hershey Script Complex — the most fluid cursive in the set. */
const FONT = 'scriptc'
/** Extra space between glyphs, in font units. Cursive wants a little air. */
const TRACKING = 0.5
/** Curve slack when refitting. Above 1 loosens the hand. */
const TENSION = 1.15

const fonts = JSON.parse(
  await readFile(join(root, 'node_modules/hersheytext/hersheytext.json'), 'utf8'),
)
const font = fonts[FONT]
if (!font) throw new Error(`Unknown Hershey font "${FONT}"`)

/** Hershey stores glyphs as M/L polylines. Pull them apart into point runs. */
function strokesFor(char) {
  if (char === ' ') return { strokes: [], advance: 8 }
  const glyph = font.chars[char.charCodeAt(0) - 33]
  if (!glyph) throw new Error(`No glyph for ${JSON.stringify(char)} in ${FONT}`)

  const strokes = []
  for (const chunk of glyph.d.split('M').slice(1)) {
    const nums = chunk.match(/-?\d+(?:\.\d+)?/g)
    if (!nums) continue
    const pts = []
    for (let i = 0; i + 1 < nums.length; i += 2) {
      pts.push({ x: Number(nums[i]), y: Number(nums[i + 1]) })
    }
    if (pts.length > 0) strokes.push(pts)
  }
  return { strokes, advance: glyph.o }
}

/** Catmull-Rom through every point, emitted as cubic beziers. */
function smooth(points, tension) {
  if (points.length < 2) return ''
  const r = (n) => Math.round(n * 100) / 100
  let d = `M ${r(points[0].x)} ${r(points[0].y)}`

  for (let i = 0; i < points.length - 1; i++) {
    const p0 = points[i - 1] ?? points[i]
    const p1 = points[i]
    const p2 = points[i + 1]
    const p3 = points[i + 2] ?? p2
    const k = tension / 6
    d +=
      ` C ${r(p1.x + (p2.x - p0.x) * k)} ${r(p1.y + (p2.y - p0.y) * k)},` +
      ` ${r(p2.x - (p3.x - p1.x) * k)} ${r(p2.y - (p3.y - p1.y) * k)},` +
      ` ${r(p2.x)} ${r(p2.y)}`
  }
  return d
}

// Lay the phrase out, collecting every stroke in writing order.
let cursor = 0
const laid = []
for (const char of PHRASE) {
  const { strokes, advance } = strokesFor(char)
  for (const stroke of strokes) {
    laid.push(stroke.map((p) => ({ x: p.x + cursor, y: p.y })))
  }
  cursor += advance + TRACKING
}

const d = laid.map((stroke) => smooth(stroke, TENSION)).join(' ')

const first = laid[0][0]
const lastStroke = laid[laid.length - 1]
const last = lastStroke[lastStroke.length - 1]
const round = (n) => Math.round(n * 100) / 100

const all = laid.flat()
const xs = all.map((p) => p.x)
const ys = all.map((p) => p.y)
const pad = 2
const viewBox = [
  Math.min(...xs) - pad,
  Math.min(...ys) - pad,
  Math.max(...xs) - Math.min(...xs) + pad * 2,
  Math.max(...ys) - Math.min(...ys) + pad * 2,
].map((n) => Math.round(n * 100) / 100)

const out = `// GENERATED by scripts/lettering.mjs — do not edit by hand.
// Re-run \`npm run lettering\` if the hero script copy changes.
//
// Single-stroke centreline built from the Hershey ${FONT} engraving font and
// refitted as smooth curves, so the thread writes the phrase rather than
// tracing the outside edge of letters.

/** Centreline strokes of the hero script phrase, in writing order. */
export const heroScriptLettering = {
  phrase: ${JSON.stringify(PHRASE)},
  d: ${JSON.stringify(d)},
  viewBox: ${JSON.stringify(viewBox.join(' '))},
  width: ${viewBox[2]},
  height: ${viewBox[3]},
  /** First and last pen positions, so the incoming and outgoing thread can
      meet the handwriting exactly instead of near it. In viewBox units. */
  start: { x: ${round(first.x)}, y: ${round(first.y)} },
  end: { x: ${round(last.x)}, y: ${round(last.y)} },
} as const
`

await writeFile(join(root, 'src/content/heroLettering.ts'), out)

console.log(`Wrote src/content/heroLettering.ts`)
console.log(`  phrase   "${PHRASE}"`)
console.log(`  font     Hershey ${FONT} (single-stroke)`)
console.log(`  strokes  ${laid.length}`)
console.log(`  viewBox  ${viewBox.join(' ')}`)
console.log(`  path     ${d.length} chars`)
