/**
 * Convert the hero's script phrase into an SVG path, so the thread can draw
 * the actual letterforms rather than pass near them.
 *
 *   node scripts/lettering.mjs
 *
 * Runs at author time, not in the browser: the generated path is committed, so
 * visitors never download a 107KB TTF or parse a font just to see the hero.
 * Re-run this whenever the hero script copy or the script font changes.
 */

import opentype from 'opentype.js'
import { readFile, writeFile } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Must match `home.hero.script` in src/content/home.en.ts. */
const PHRASE = 'The same cloth,'
const FONT_SIZE = 200

const buf = await readFile(join(root, 'src/assets/fonts/Allura-Regular.ttf'))
const font = opentype.parse(
  buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength),
)

// Baseline at y = 0; the viewBox below re-frames it.
const path = font.getPath(PHRASE, 0, 0, FONT_SIZE)
const d = path.toPathData(2)
const { x1, y1, x2, y2 } = path.getBoundingBox()

const pad = 6
const viewBox = [x1 - pad, y1 - pad, x2 - x1 + pad * 2, y2 - y1 + pad * 2].map((n) =>
  Math.round(n * 100) / 100,
)

const out = `// GENERATED by scripts/lettering.mjs — do not edit by hand.
// Re-run \`npm run lettering\` if the hero script copy or font changes.

/** Outlines of the hero script phrase, as drawn in Allura. */
export const heroScriptLettering = {
  phrase: ${JSON.stringify(PHRASE)},
  d: ${JSON.stringify(d)},
  viewBox: ${JSON.stringify(viewBox.join(' '))},
  width: ${viewBox[2]},
  height: ${viewBox[3]},
} as const
`

await writeFile(join(root, 'src/content/heroLettering.ts'), out)

console.log(`Wrote src/content/heroLettering.ts`)
console.log(`  phrase   "${PHRASE}"`)
console.log(`  viewBox  ${viewBox.join(' ')}`)
console.log(`  path     ${d.length} chars`)
